import { Template } from '@/types';

export const STOCK_TEMPLATES: Template[] = [
    {
        id: 'modern-bold',
        name: 'Modern Bold',
        ratio: '9:16',
        fontFamily: 'Inter',
        fontSize: 72,
        textColor: '#FFFFFF',
        activeWordColor: '#A855F7',
        strokeColor: '#000000',
        strokeWidth: 4,
        backgroundMode: 'blur',
        backgroundColor: '#000000',
        backgroundBlur: 10,
        animationIn: 'zoom',
        animationOut: 'fade',
        highlightMode: 'word',
        positionY: 50,
        safeArea: true
    },
    {
        id: 'karaoke-classic',
        name: 'Karaoke Classic',
        ratio: '16:9',
        fontFamily: 'Roboto',
        fontSize: 60,
        textColor: '#FFFFFF',
        activeWordColor: '#FFFF00',
        strokeColor: '#000000',
        strokeWidth: 2,
        backgroundMode: 'color',
        backgroundColor: '#000000',
        backgroundBlur: 0,
        animationIn: 'slide-up',
        animationOut: 'none',
        highlightMode: 'line',
        positionY: 80,
        safeArea: false
    },
    {
        id: 'minimal-lounge',
        name: 'Minimal Lounge',
        ratio: '9:16',
        fontFamily: 'Outfit',
        fontSize: 48,
        textColor: '#E5E7EB',
        activeWordColor: '#F472B6',
        strokeColor: 'transparent',
        strokeWidth: 0,
        backgroundMode: 'transparent',
        backgroundColor: '#0E1117',
        backgroundBlur: 0,
        animationIn: 'fade',
        animationOut: 'fade',
        highlightMode: 'word',
        positionY: 50,
        safeArea: true
    },
    {
        id: 'neon-vibe',
        name: 'Neon Vibe',
        ratio: '9:16',
        fontFamily: 'Montserrat',
        fontSize: 80,
        textColor: '#333333',
        activeWordColor: '#00FBFF',
        strokeColor: '#00FBFF',
        strokeWidth: 1,
        backgroundMode: 'color',
        backgroundColor: '#000000',
        backgroundBlur: 0,
        glowColor: '#00FBFF',
        glowRadius: 20,
        animationIn: 'zoom',
        animationOut: 'zoom',
        highlightMode: 'word',
        positionY: 45,
        safeArea: true
    },
    {
        id: 'story-teller',
        name: 'Story Teller',
        ratio: '9:16',
        fontFamily: 'Playfair Display',
        fontSize: 64,
        textColor: '#F3F4F6',
        activeWordColor: '#FFFFFF',
        strokeColor: 'transparent',
        strokeWidth: 0,
        backgroundMode: 'blur',
        backgroundColor: '#111827',
        backgroundBlur: 20,
        animationIn: 'slide-up',
        animationOut: 'slide-down',
        highlightMode: 'line',
        positionY: 70,
        safeArea: true
    }
];
