import { Template } from '@/src/schemas';

export const TEMPLATES_REGISTRY = [
    {
        id: 'minimal-clean',
        name: 'Minimal Clean',
        category: 'Clean',
        ratio: '9:16',
        fontFamily: 'Inter',
        fontSize: 64,
        fontWeight: '500',
        textColor: '#FFFFFF',
        activeWordColor: '#D1D5DB',
        strokeColor: 'transparent',
        strokeWidth: 0,
        alignment: 'center',
        position: { x: 50, y: 50 },
        animationIn: 'fade',
        animationOut: 'fade',
        highlightMode: 'word',
        backgroundMode: 'color',
        backgroundColor: '#000000',
        backgroundBlur: 0,
        safeArea: true,
        glow: false,
        blur: false,
        shadow: false
    },
    {
        id: 'glow-karaoke',
        name: 'Glow Karaoke',
        category: 'Vibrant',
        ratio: '9:16',
        fontFamily: 'Montserrat',
        fontSize: 72,
        fontWeight: '800',
        textColor: '#FFFFFF',
        activeWordColor: '#A855F7',
        glow: true,
        glowColor: '#A855F7',
        glowRadius: 20,
        alignment: 'center',
        position: { x: 50, y: 50 },
        animationIn: 'zoom',
        animationOut: 'zoom',
        highlightMode: 'word',
        backgroundMode: 'blur',
        backgroundColor: '#000000',
        backgroundBlur: 10,
        safeArea: true,
        blur: false,
        shadow: false
    },
    {
        id: 'social-reels-bold',
        name: 'Social Reels Bold',
        category: 'Social',
        ratio: '9:16',
        fontFamily: 'Archivo Black',
        fontSize: 80,
        fontWeight: '900',
        textColor: '#FFFFFF',
        activeWordColor: '#FACC15',
        strokeColor: '#000000',
        strokeWidth: 4,
        alignment: 'center',
        position: { x: 50, y: 45 },
        animationIn: 'slide-up',
        animationOut: 'slide-down',
        highlightMode: 'word',
        backgroundMode: 'transparent',
        backgroundColor: '#000000',
        backgroundBlur: 0,
        safeArea: true,
        glow: false,
        blur: false,
        shadow: false
    },
    {
        id: 'dark-cinematic',
        name: 'Dark Cinematic',
        category: 'Movie',
        ratio: '16:9',
        fontFamily: 'Playfair Display',
        fontSize: 56,
        fontWeight: '400',
        textColor: '#F3F4F6',
        activeWordColor: '#FFFFFF',
        alignment: 'center',
        position: { x: 50, y: 80 },
        animationIn: 'fade',
        animationOut: 'fade',
        highlightMode: 'line',
        backgroundMode: 'blur',
        backgroundColor: '#000000',
        backgroundBlur: 20,
        safeArea: true,
        glow: false,
        blur: false,
        shadow: false
    },
    {
        id: 'spotify-style',
        name: 'Spotify Style Inspired',
        category: 'Music',
        ratio: '9:16',
        fontFamily: 'Inter',
        fontSize: 60,
        fontWeight: '700',
        textColor: 'rgba(255,255,255,0.4)',
        activeWordColor: '#FFFFFF',
        alignment: 'left',
        position: { x: 10, y: 60 },
        animationIn: 'slide-up',
        animationOut: 'none',
        highlightMode: 'word',
        backgroundMode: 'color',
        backgroundColor: '#1DB954',
        backgroundBlur: 0,
        safeArea: true,
        glow: false,
        blur: false,
        shadow: false
    },
    {
        id: 'neon-pulse',
        name: 'Neon Pulse',
        category: 'Vibrant',
        ratio: '9:16',
        fontFamily: 'Inter',
        fontSize: 68,
        fontWeight: '700',
        textColor: '#22D3EE',
        activeWordColor: '#FFFFFF',
        strokeColor: '#22D3EE',
        strokeWidth: 1,
        glow: true,
        glowColor: '#22D3EE',
        glowRadius: 15,
        alignment: 'center',
        position: { x: 50, y: 50 },
        animationIn: 'zoom',
        animationOut: 'none',
        highlightMode: 'word',
        backgroundMode: 'color',
        backgroundColor: '#000000',
        backgroundBlur: 0,
        safeArea: true,
        blur: false,
        shadow: false
    },
    {
        id: 'elegant-serif',
        name: 'Elegant Serif',
        category: 'Classic',
        ratio: '9:16',
        fontFamily: 'Inter',
        fontSize: 52,
        fontWeight: '300',
        textColor: '#FEF3C7',
        activeWordColor: '#FFFFFF',
        alignment: 'center',
        position: { x: 50, y: 50 },
        animationIn: 'fade',
        animationOut: 'none',
        highlightMode: 'line',
        backgroundMode: 'blur',
        backgroundColor: '#451a03',
        backgroundBlur: 30,
        safeArea: true,
        glow: false,
        blur: false,
        shadow: false
    },
    {
        id: 'performance-stage',
        name: 'Performance Stage',
        category: 'Events',
        ratio: '16:9',
        fontFamily: 'Inter',
        fontSize: 120,
        fontWeight: '400',
        textColor: '#FFFFFF',
        activeWordColor: '#F87171',
        strokeColor: '#000000',
        strokeWidth: 2,
        alignment: 'center',
        position: { x: 50, y: 50 },
        animationIn: 'zoom',
        animationOut: 'none',
        highlightMode: 'word',
        backgroundMode: 'transparent',
        backgroundColor: '#000000',
        backgroundBlur: 0,
        safeArea: false,
        glow: false,
        blur: false,
        shadow: false
    },
    {
        id: 'kinetic-neon',
        name: 'Kinetic Neon',
        category: 'Premium',
        ratio: '9:16',
        fontFamily: 'Orbitron',
        fontSize: 80,
        fontWeight: '900',
        textColor: '#FFFFFF',
        activeWordColor: '#00F2FF',
        glow: true,
        glowColor: '#00F2FF',
        glowRadius: 30,
        alignment: 'center',
        position: { x: 50, y: 50 },
        textBehavior: { mode: 'word_by_word', scrollDirection: 'none' },
        visualFx: { wordGlow: true, chromaticAberration: 1.5, vignette: 0.4 },
        cameraMotion: { preset: 'micro_shake', intensity: 1 }
    },
    {
        id: 'cinematic-worship',
        name: 'Cinematic Worship',
        category: 'Premium',
        ratio: '16:9',
        fontFamily: 'Playfair Display',
        fontSize: 48,
        fontWeight: '400',
        textColor: '#FFFFFF',
        activeWordColor: '#FFFFFF',
        alignment: 'center',
        position: { x: 50, y: 80 },
        textBehavior: { mode: 'rolling_lines', scrollDirection: 'vertical', maxLinesVisible: 2 },
        visualFx: { wordBlurIn: true, vignette: 0.8 },
        cameraMotion: { preset: 'zoom_drift', intensity: 0.8 }
    },
    {
        id: 'aggressive-trap-roll',
        name: 'Aggressive Trap Roll',
        category: 'Premium',
        ratio: '9:16',
        fontFamily: 'Archivo Black',
        fontSize: 90,
        fontWeight: '900',
        textTransform: 'uppercase',
        textColor: '#FFFFFF',
        activeWordColor: '#FF0000',
        alignment: 'center',
        position: { x: 50, y: 50 },
        textBehavior: { mode: 'word_by_word' },
        visualFx: { wordShake: true, strokeFlash: true, grain: 0.2 },
        cameraMotion: { preset: 'push_in', intensity: 1.5 }
    },
    {
        id: 'luxury-minimal-motion',
        name: 'Luxury Minimal Motion',
        category: 'Premium',
        ratio: '9:16',
        fontFamily: 'Inter',
        fontSize: 60,
        fontWeight: '200',
        letterSpacing: 4,
        textColor: 'rgba(255,255,255,0.6)',
        activeWordColor: '#D4AF37',
        alignment: 'center',
        position: { x: 50, y: 50 },
        textBehavior: { mode: 'karaoke_bar' },
        visualFx: { vignette: 0.5, grain: 0.1 },
        cameraMotion: { preset: 'parallax', intensity: 0.5 }
    }
] as unknown as Template[];
