import { Template } from '@/src/schemas';

export const TEMPLATES_REGISTRY = [
    {
        id: 'minimal-clean',
        name: 'Minimal Clean',
        category: 'Clean',
        ratio: '9:16',
        fontFamily: 'Inter',
        fontSize: 64,
        fontWeight: '500',
        textColor: '#FFFFFF',
        activeWordColor: '#D1D5DB',
        strokeColor: 'transparent',
        strokeWidth: 0,
        alignment: 'center',
        position: { x: 50, y: 50 },
        animationIn: 'fade',
        animationOut: 'fade',
        highlightMode: 'word',
        backgroundMode: 'color',
        backgroundColor: '#000000',
        backgroundBlur: 0,
        safeArea: true,
        glow: false,
        blur: false,
        shadow: false
    },
    {
        id: 'glow-karaoke',
        name: 'Glow Karaoke',
        category: 'Vibrant',
        ratio: '9:16',
        fontFamily: 'Montserrat',
        fontSize: 72,
        fontWeight: '800',
        textColor: '#FFFFFF',
        activeWordColor: '#A855F7',
        glow: true,
        glowColor: '#A855F7',
        glowRadius: 20,
        alignment: 'center',
        position: { x: 50, y: 50 },
        animationIn: 'zoom',
        animationOut: 'zoom',
        highlightMode: 'word',
        backgroundMode: 'blur',
        backgroundColor: '#000000',
        backgroundBlur: 10,
        safeArea: true,
        blur: false,
        shadow: false
    },
    {
        id: 'social-reels-bold',
        name: 'Social Reels Bold',
        category: 'Social',
        ratio: '9:16',
        fontFamily: 'Archivo Black',
        fontSize: 80,
        fontWeight: '900',
        textColor: '#FFFFFF',
        activeWordColor: '#FACC15',
        strokeColor: '#000000',
        strokeWidth: 4,
        alignment: 'center',
        position: { x: 50, y: 45 },
        animationIn: 'slide-up',
        animationOut: 'slide-down',
        highlightMode: 'word',
        backgroundMode: 'transparent',
        backgroundColor: '#000000',
        backgroundBlur: 0,
        safeArea: true,
        glow: false,
        blur: false,
        shadow: false
    },
    {
        id: 'dark-cinematic',
        name: 'Dark Cinematic',
        category: 'Movie',
        ratio: '16:9',
        fontFamily: 'Playfair Display',
        fontSize: 56,
        fontWeight: '400',
        textColor: '#F3F4F6',
        activeWordColor: '#FFFFFF',
        alignment: 'center',
        position: { x: 50, y: 80 },
        animationIn: 'fade',
        animationOut: 'fade',
        highlightMode: 'line',
        backgroundMode: 'blur',
        backgroundColor: '#000000',
        backgroundBlur: 20,
        safeArea: true,
        glow: false,
        blur: false,
        shadow: false
    },
    {
        id: 'spotify-style',
        name: 'Spotify Style Inspired',
        category: 'Music',
        ratio: '9:16',
        fontFamily: 'Inter',
        fontSize: 60,
        fontWeight: '700',
        textColor: 'rgba(255,255,255,0.4)',
        activeWordColor: '#FFFFFF',
        alignment: 'left',
        position: { x: 10, y: 60 },
        animationIn: 'slide-up',
        animationOut: 'none',
        highlightMode: 'word',
        backgroundMode: 'color',
        backgroundColor: '#1DB954',
        backgroundBlur: 0,
        safeArea: true,
        glow: false,
        blur: false,
        shadow: false
    },
    {
        id: 'neon-pulse',
        name: 'Neon Pulse',
        category: 'Vibrant',
        ratio: '9:16',
        fontFamily: 'Inter',
        fontSize: 68,
        fontWeight: '700',
        textColor: '#22D3EE',
        activeWordColor: '#FFFFFF',
        strokeColor: '#22D3EE',
        strokeWidth: 1,
        glow: true,
        glowColor: '#22D3EE',
        glowRadius: 15,
        alignment: 'center',
        position: { x: 50, y: 50 },
        animationIn: 'zoom',
        animationOut: 'none',
        highlightMode: 'word',
        backgroundMode: 'color',
        backgroundColor: '#000000',
        backgroundBlur: 0,
        safeArea: true,
        blur: false,
        shadow: false
    },
    {
        id: 'elegant-serif',
        name: 'Elegant Serif',
        category: 'Classic',
        ratio: '9:16',
        fontFamily: 'Inter',
        fontSize: 52,
        fontWeight: '300',
        textColor: '#FEF3C7',
        activeWordColor: '#FFFFFF',
        alignment: 'center',
        position: { x: 50, y: 50 },
        animationIn: 'fade',
        animationOut: 'none',
        highlightMode: 'line',
        backgroundMode: 'blur',
        backgroundColor: '#451a03',
        backgroundBlur: 30,
        safeArea: true,
        glow: false,
        blur: false,
        shadow: false
    },
    {
        id: 'performance-stage',
        name: 'Performance Stage',
        category: 'Events',
        ratio: '16:9',
        fontFamily: 'Inter',
        fontSize: 120,
        fontWeight: '400',
        textColor: '#FFFFFF',
        activeWordColor: '#F87171',
        strokeColor: '#000000',
        strokeWidth: 2,
        alignment: 'center',
        position: { x: 50, y: 50 },
        animationIn: 'zoom',
        animationOut: 'none',
        highlightMode: 'word',
        backgroundMode: 'transparent',
        backgroundColor: '#000000',
        backgroundBlur: 0,
        safeArea: false,
        glow: false,
        blur: false,
        shadow: false
    }
] as unknown as Template[];
